services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sabhyatam
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sabhyatam"]
      interval: 3s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6380:6379"

  product-migrate:
    build:
      context: ./services/product
      dockerfile: Dockerfile.migrate
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/sabhyatam?sslmode=disable
    restart: "no"

  product-seed:
    build:
      context: ./services/product
      dockerfile: Dockerfile.seed
    depends_on:
      product-migrate:
        condition: service_completed_successfully
    environment:
      DB: postgres://postgres:postgres@postgres:5432/sabhyatam?sslmode=disable
    command: ["node", "import_seed.js"]
    restart: "no"

  orders-migrate:
    image: postgres:15
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./services/orders/migration:/migrations
    entrypoint: >
      sh -c "
      until pg_isready -h postgres -p 5432; do sleep 1; done &&
      psql postgres://postgres:postgres@postgres:5432/sabhyatam?sslmode=disable
      -f /migrations/001_create_orders.sql
      "
    restart: "no"

  product:
    build: ./services/product
    container_name: product
    depends_on:
      product-seed:
        condition: service_completed_successfully
    env_file:
      - ./services/product/.env
    ports:
      - "8080:8080"

  cart:
    build: ./services/cart
    container_name: cart
    env_file:
      - ./services/cart/.env
    depends_on:
      product:
        condition: service_started
      redis:
        condition: service_started
    ports:
      - "8081:8081"

  orders:
    build: ./services/orders
    container_name: orders
    env_file:
      - ./services/orders/.env
    depends_on:
      orders-migrate:
        condition: service_completed_successfully
      product:
        condition: service_started
      cart:
        condition: service_started
    ports:
      - "8082:8082"

volumes:
  pgdata:
