version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sabhyatam

    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  productsvc:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PRODUCTSVC_PORT: "8080"
      DATABASE_URL: {DATABASE_URL}
      ADMIN_KEY: {ADMIN_KEY}
      AWS_REGION: {AWS_REGION}
      AWS_BUCKET_NAME: {AWS_BUCKET_NAME}
      AWS_ACCESS_KEY_ID: {AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: {AWS_SECRET_ACCESS_KEY}


    ports:
      - "8080:8080"
    volumes:
      - ./:/src

volumes:
  pgdata:
